# Generated by Django 5.0.6 on 2024-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('expiration', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
