# Generated by Django 5.0.6 on 2024-06-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0.0)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.CharField(default='images/default-vinyl-photo.webp', max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.vinyl')),
            ],
        ),
        migrations.CreateModel(
            name='VinylCategory',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.category')),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.vinyl')),
            ],
        ),
    ]
